name: Release

on:
  push:
    branches:
      - "master"
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      output: "${{ github.workspace }}/app/build/outputs/apk/release"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.4
          cache: false
          cache-dependency-path: ${{ github.workspace }}/alist-lib/go.sum

      - uses: actions/cache@v3
        name: Cache Go Modules
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-

      - name: Build Alist-lib
        run: |
          cd alist-lib/scripts
          chmod +x *.sh

          ./install_alist.sh
          ./install_web.sh

          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init 
          go get golang.org/x/mobile/bind
          ./install_aar.sh all

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: BuildArtifacts
          path: target/
